### ISSUE TITLE
Simulating Velodyne HDL-64 E LiDAR sensor

### ISSUE THREAD

**Issue by hitman996** [UsmanJafri/LiDAR-GTA-V#7]
Hi @UsmanJafri , 
     I am trying to simulate [Velodyne Lidar] used for KITTI benchmark(https://velodynelidar.com/hdl-64e.html) inside GTA5. Your config file provided has the rest of the parameters inside which was great. But the above shown LiDAR has 
1. 64 channels and 

additional parameters which I want to simulate for GTA5 as well. If I understand correctly, this will also lead to variable number of points at the output for each snapshot(which is what I desire). Do you have any suggestions for me on how to approach this problem? Thank you in advance and appreciate your work.

**Comment by UsmanJafri** [comment]
Hi @hitman996,

The number of channels represents the number of laser emitters and detectors arranged in the vertical FOV.
So for the HDL64e sensor, a vertical FOV of 26.9 degrees with 64 channels means that there must be a spacing of 0.42 degrees vertically between laser rays. Since `26.9 / 64 = 0.42`

This can be verified by viewing the[ official HDL64e datasheet](https://velodynelidar.com/docs/datasheet/63-9194_Rev-J_HDL-64E_S3_Spec%20Sheet%20Web.pdf) which reports the vertical resolution as 0.4 degrees.

Therefore to simulate the 64 channels using [LiDAR-GTA-V](https://github.com/UsmanJafri/LiDAR-GTA-V/) you can set `Vertical_Step = 0.42` in the [LiDAR GTA V.cfg](https://github.com/UsmanJafri/LiDAR-GTA-V/blob/master/LiDAR%20GTA%20V/bin/Release/LiDAR%20GTA%20V/LiDAR%20GTA%20V.cfg) file.
